# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 625ee9a216f8890c8c583fb0ffff07252bc68831e7605d3d88a28f2ae929007c25d619c153e471423126262b424f9cf71cd3ea6d4f3db8f804314c6720783be7

test:
  secret_key_base: 398aadac62a264996cc55cc9703b8b8717bbf7ab03b9eda0330a9d263b2105e1e550746f3f0450381afee58d48a982c95107b03a40103f787c9d30a19b4b16bc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
